export const helperConstants = {
  THEME_CHANGE_REQUEST: "THEME_CHANGE_REQUEST",
  MARGIN_CHANGE_REQUEST: "MARGIN_CHANGE_REQUEST",
};

export const categoryConstants = {
  GET_CATEGORIES_REQUEST: "GET_CATEGORIES_REQUEST",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",
};
